const Menu = [
    {
      id: 1,
      image: "./../../../public/images/student1.webp",
      name: "Sohel",
      category: "student",
      classes: "Class: Seven",
    },
    {
      id: 1,
      image: "./../../../public/images/student2.jpg",
      name: "Nabil",
      category: "student",
      classes: "Class: eight",
    },
    {
      id: 1,
      image: "./../../../public/images/student3.jpg",
      name: "Akif",
      category: "student",
      classes: "Class: nine",
    },
    {
      id: 1,
      image: "./../../../public/images/student5.jpeg",
      name: "Sanira",
      category: "student",
      classes: "Class: ten",
    },
    {
      id: 1,
      image: "./../../../public/images/parent4.jpg",
      name: "Abdul Alim",
      category: "parent",
      classes: "business man",
    },
    {
      id: 1,
      image: "./../../../public/images/parent1.jpg",
      name: "Nazma Aktar",
      category: "parent",
      classes: "house wife",
    },
    {
      id: 1,
      image: "./../../../public/images/parent2.jfif",
      name: "Sohely Biswas",
      category: "parent",
      classes: "house wife",
    },
    {
      id: 1,
      image: "./../../../public/images/parent3.jpg",
      name: "Joly Khan",
      category: "parent",
      classes: "business woman",
    },
    {
      id: 1,
      image: "./../../../public/images/stuff1.jpg",
      name: "Sephali",
      category: "stuff",
    },
    {
      id: 1,
      image: "./../../../public/images/stuff2.jfif",
      name: "Rakhi",
      category: "stuff",
    },
    {
      id: 1,
      image: "./../../../public/images/stuff3.jpg",
      name: "Nazim",
      category: "stuff",
    },
    {
      id: 2,
      image: "./../../../public/images/stuff4.jpg",
      name: "Mahim",
      category: "stuff",
    },
    {
      id: 3,
      image: "./../../../public/images/teacher1.jfif",
      name: "Ashim Biswas",
      category: "teacher",
      classes: "subject: science",
    },
    {
      id: 4,
      image: "./../../../public/images/teacher2.jpg",
      name: "Shakti Khan",
      category: "teacher",
      classes: "subject: math",
    },
    {
      id: 5,
      image: "./../../../public/images/teacher3.jfif",
      name: "Atik Islam",
      category: "teacher",
      classes: "subject: Bangla",
    },
    {
      id: 6,
      image: "./../../../public/images/teacher4.jpg",
      name: "Akter Islam",
      category: "parent",
      classes: "Doctor",
    },
    {
      id: 7,
      image: "./../../../public/images/teacher5.webp",
      name: "Halima",
      category: "parent",
      classes: "house wife",
    },
    {
      id: 8,
      image: "./../../../public/images/teacher6.jfif",
      name: "Shapla Akter",
      category: "parent",
      classes: "house wife",
      
    },
    {
      id: 9,
      image: "./../../../public/images/teacher7.jpg",
      name: "Mariya",
      category: "teacher",
      classes: "subject: English",
    }
  ];
  
  export default Menu;